name: 'riskmetric'
version: '1.0.0'
config-version: 2

profile: 'riskmetric'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  riskmetric:
    staging:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
